### ISSUE TITLE
SQLファイル関連

### ISSUE THREAD

**Issue by thonma** [skj-kensyu-2018/ojihome#15]
+ [ ] 以下のファイルをcreate.sqlに統合する(以下のファイルは統合後、削除する)
usersテーブルは仕様上は不要ですが、CRUDサンプルが動かなくなってしまうので入れておいてください。
    + /category_Insert.sql
    + /comment_Insert.sql
    + /new_create.sql
+ [ ] 各テーブルのcreated、modifiedカラムにデフォルト値にNULLを設定する(NOT NULLは無くす)
+ [ ] categoriesテーブルのINSERT文を実行するとエラーになるので修正する
+ [ ] commentsテーブルのINSERT文を実行するとエラーになるので修正する

**Comment by miosawara** [comment]
create.sqlに統合しました。
テーブルのcreated、modifiedカラムはdefault　nullに修正。
エラーも修正済み
