### ISSUE TITLE
ほめ管理TOPのURLが実際の表示内容と異なる

### ISSUE THREAD

**Issue by thonma** [skj-kensyu-2018/ojihome#20]
基本的に、URLから画面名や機能が推測できるようにしておくと良い。
+ 現状：「/ojihome/hometop/top」
+ 理想(?)：「/ojihome/management」

**Comment by takachanchan** [comment]
Missing View
Error: The view for ManagementController::index() was not found.

Confirm you have created the file: Management\index.php	in one of the following paths:

**Comment by takachanchan** [comment]
controller内にマネジメントコントローラを作成し、
view内でmanagement.phpを作成したのですが、エラーが出てしまいました。
ご指導ください。


Missing View
Error: The view for ManagementController::index() was not found.

Confirm you have created the file: Management\index.php	in one of the following paths:
