### ISSUE TITLE
褒める画面で「お前を褒める言葉などない」が出るとき、文字を一つずつ並べる

### ISSUE THREAD

**Issue by thonma** [skj-kensyu-2018/ojihome#61]

**Comment by takachanchan** [comment]
[HomeruController]
上部
<form name="timer">
<input type="button" value="スタート" onclick="startfnc()"><br>
<input type="text" name="moji" size="30" value="">
</form>

下部
<?php
echo $this->Html->script ( "omahome.js" );
?>

**Comment by takachanchan** [comment]
[omahome.js]

function word()
{
  //表示する文字
  var str = word();

  //テキストボックスの文字数
  var count = document.timer.moji.value.length;

  //文字が全部表示されているか確認
  if ( count < 11 )
  {
    //現在より1文字多く切り出して表示
    document.timer.moji.value = str.substr(0,count+1);
  }
  else
  {
    //全て表示されたら、空文字に戻す
    document.timer.moji.value = "";
  }
  console.log(word);
}


function startfnc()
{
  //関数hyoji()を1000ミリ秒間隔で呼び出す
  setInterval("word()",1000);
}

**Comment by takachanchan** [comment]
https://www.pazru.net/js/timer/1.html

**Comment by takachanchan** [comment]
Fatal Error
Error: Using $this when not in object context	
File: C:\k2018workspacephp\pleiades\xampp\htdocs\ojihome\app\Controller\HomeruController.php	
Line: 79

**Comment by takachanchan** [comment]
<?php
echo $this->Html->script ( "omahome.js" );
?>
