### ISSUE TITLE
「もう一度ほめてもらう」機能をAjax化

### ISSUE THREAD

**Issue by takachanchan** [skj-kensyu-2018/ojihome#70]
ほめ画面で「もう一度ほめてもらう」を押した時、画面を切り替えずに、Ajaxを使って同じ機能を実装する

**Comment by thonma** [comment]
「画面が切り替わらない」では結局何をすればいいのか不明です。
「画面を切り替えずに、Ajaxを使って同じ機能を実装する」で良いと思います。

**Comment by takachanchan** [comment]
修正します

**Comment by thonma** [comment]
あとで見ても、タイトルから概要が分かるように、以下のように修正してください。
タイトル：「もう一度ほめてもらう」機能をAjax化

**Comment by takachanchan** [comment]
いまAjax機能を実装するためにサイトを見ながら考えているのですが、Ajaxを実装させる方法がいくつかあり、どちらが正しのか分かりません。下記にリンクを貼るので、ご査収の上、どちらで実装させるのがいいのかご教授ください。
https://www.sejuku.net/blog/30245
https://qiita.com/hisamura333/items/e3ea6ae549eb09b7efb9

**Comment by takachanchan** [comment]
ちなみに、個人的には
https://www.sejuku.net/blog/30245
の方が理解しやすいのですが、このサイトの実装方法は
誤っていますか。

**Comment by thonma** [comment]
```
ちなみに、個人的には
https://www.sejuku.net/blog/30245
の方が理解しやすいのですが、このサイトの実装方法は
誤っていますか。
```
誤っていないと思います。
ただし、XMLHttpRequest()ではなくjQueryを使う方法の方が一般的です。

**Comment by thonma** [comment]
https://www.sejuku.net/blog/30245#jQueryAjax
上記のサンプルですね

**Comment by takachanchan** [comment]
かしこまりました。
ありがとうございます。
